### ISSUE TITLE
Emit test cases before test run starts

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/compatibility-kit#112]
For a test run with 3 test cases, the order of events relating to test cases and the test run looks like this (omitting actual test steps and attachments for brevity):

1. TestRunStarted
2. TestCase
3. TestCase
4. TestCase
5. TestCaseStarted
6. TestCaseFinished
7. TestCaseStarted
8. TestCaseFinished
9. TestCaseStarted
10. TestCaseFinished
11. TestRunFinished

There are some reasons why we might want to change this to:

1. TestCase
2. TestCase
3. TestCase
4. TestRunStarted
5. TestCaseStarted
6. TestCaseFinished
7. TestCaseStarted
8. TestCaseFinished
9. TestCaseStarted
10. TestCaseFinished
11. TestRunFinished

Specifically:

- In theory, you could execute multiple test runs from the same set of test cases (https://github.com/cucumber/messages/pull/102 brings this closer to reality, with the `TestRunStarted` having an id)
- The time spent assembling test cases contributes to the test run time, which you might expect to only cover the actual execution
- It can cause some uncomfortable coupling in code (not that users would care)

If we think the suggested change is better, we can change `fake-cucumber` and then update the CCK. (From a `cucumber-js` perspective I would quite like to change this, but don't feel very strongly.)

**Comment by clrudolphi** [comment]
At least for the .NET implementations, this will (further) complicate the implementation of Messages support.
A TestCase is not solely derived from the content of the Feature, but is the dynamically aggregated result of matching that Feature against the known StepDefinition implementations and Hooks (some of which are conditionally executed based upon Tag expressions).
In other words, we have to actually execute the TestCase in order to identify which TestSteps belong to it.

So publishing the TestCase before the TestRunStarted is misleading. It can't be determined until the TestRun _has_ started.
(NB, in the .NET implementation, we can't publish a TestCase message until after the completion of that TestCase. We defer publication of TestStepStarted/Finished until after the TestCase is complete in order to preserve the relational integrity between them)

And by "you could execute multiple test runs from the same set of test cases", do you mean via a Retry mechanism or by some other means (in which we could or could not guarantee that the Tag expressions will result in stable results)? In other words, can we be sure that TestCases emitted outside the scope of a TestRun are reusable?
